### ISSUE TITLE
8.2: The app implements prevents

### ISSUE THREAD

**Issue by Sjord** [OWASP/owasp-masvs#103]
There seems to be a typo in [8.2](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md): 

> 8.2: The app implements prevents debugging and/or detects, and responds 
to, a debugger being attached. All available debugging protocols must be
 covered.

Here, "implements prevents" seems incorrect.

**Comment by sushi2k** [comment]
True. "implements" should be removed. Just made the change https://github.com/OWASP/owasp-masvs/commit/8ee350ac3ebb15dc763b22bf246460c76f6515d1

Thanks @Sjord

**Comment by Sjord** [comment]
👍
