### ISSUE TITLE
Only certificates signed by a valid CA are accepted.

### ISSUE THREAD

**Issue by Sjord** [OWASP/owasp-masvs#105]
[V5.3](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x10-V5-Network_communication_requirements.md) says:

> The app verifies the X.509 certificate of the remote endpoint when the secure channel is established. Only certificates signed by a valid CA are accepted.

I think "valid CA" is not specific enough. Does this mean the CA's trusted by the OS? Is it OK if I create my own CA?

**Comment by sushi2k** [comment]
You are right, it should be like this:

"Only certificates known by the OS that are available in the certificate trust store are accepted."

Creating your own CA is covered in requirement 5.4. "The app either uses its own certificate store, or pins the endpoint certificate or public key, and subsequently does not establish connections with endpoints that offer a different certificate or key, even if signed by a trusted CA."

**Comment by Sjord** [comment]
I think 5.3 should also allow using your own CA. If you change 5.3 to include "Only certificates known by the OS that are available in the certificate trust store are accepted.", it is not possible to conform to 5.3 with a own CA, even if you do confirm to 5.4.

Maybe changing "valid CA" to "trusted CA" is enough, and then the application owner can choose which CA's to trust.

**Comment by b-mueller** [comment]
Fixed.
