### ISSUE TITLE
8.9 and 8.12 are exactly the same

### ISSUE THREAD

**Issue by gerardocanedo** [OWASP/owasp-masvs#112]
It should be merged in one item.

IMO it should be inside Impede Comprehension

**Comment by sushi2k** [comment]
True :-)

@b-mueller: I would remove 8.9, as this requirement fit's better into "Impede Comprehension". This is the requirement:
> All executable files and libraries belonging to the app are either encrypted on the file level and/or important code and data segments inside the executables are encrypted or packed. Trivial static analysis does not reveal important code or data.
