### ISSUE TITLE
2. Data storage -> Don't store sensitive info world-readable ?

### ISSUE THREAD

**Issue by TheDauntless** [OWASP/owasp-masvs#119]
Currently, there is no issue that indicates that an application should not store sensitive information in world-readable files.

For example, an application could use `File.createTempFile(“filename”, “pdf”, context.externalCacheDir)` to create a file, which is then used to store sensitive information. This file would not be part of a backup (assume backup="false"), but it would be world readable on the device.

This falls in between the cracks of the different controls, since documents aren't credentials (and can’t be stored in credential storage facilities (2.1)), they wouldn’t be part of backup (since backup = false in manifest, 2.8) and not kept in memory (2.10). However, after a theft + root, you have access to the documents, or even a malicious app with global read permissions.

Suggestion:

    2.13 No sensitive data is stored in a world-readable location.

This is mentioned in the testing guide, by the way: https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md -> External storage.

I can create a PR if accepted.

**Comment by jmanico** [comment]
Why not set a positive rule stating •where• to store sensitive data as opposed to negative rules stating bad locations to store data?

•drops the mike•

--
Jim Manico
@Manicode

**Comment by TheDauntless** [comment]
Fair point. It seems to break the current style of the issues, but I don't see what that should be an issue.

    2.13 Sensitive data shall be stored inside the application container.

We could take it one step further while we're at it, and say

    2.13 Sensitive data shall be encrypted when at rest, and stored inside the application container.

**Comment by jmanico** [comment]
My understanding is the “app container” is to general for sensitive data storage in mobile. For example in iOS the keychain is typically cited as the right place to store sensitive data. Is the “app container” good enough for this requirement?

--
Jim Manico
@Manicode

**Comment by sushi2k** [comment]
Hi @TheDauntless. 

thanks for pointing that out. This is already part of requirement 2.1 and described in detail in the MSTG. Please see here https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#static-analysis 

If you need to store sensitive information use the KeyChain/Keystore to encrypt it, otherwise don't store it. World-readable is definitely a no-go and I would see it as being part of the best practices you need to check as part of 2.1.

**Comment by TheDauntless** [comment]
Hi @sushi2k 

Thanks for your feedback!

I definitely agree that this is explained correctly in the MSTG. However, I do not think "reading MSTG" should be a requirement for correctly understanding the MASVS. Shouldn't MASVS, in principle, be an "on its own" checklist? I feel like now, you could have a "MASVS compliant app", that has pretty big security holes (e.g. sensitive pdfs stored in /sdcard).

2.1 is probably the one that comes closest to covering this, however, the way it is formulated seems to be solely about how to store credentials, passwords, etc. It does not imply that "anything you can't put in a central credential storage should be encrypted, stored in your private folders, and the key should be put in that credential storage". (Or maybe it _implies_ it, but shouldn't it be a little bit more obvious?)

    2.1 System credential storage facilities are used appropriately to store sensitive data, such as user credentials or cryptographic keys.

How I see it, there are two requirements that should/could be added, on their own or merged with another one:

* Encrypt any locally stored files, and store the key appropriately
* Don't store non-public files outside of the application container

**Comment by sushi2k** [comment]
Hi @TheDauntless,

sorry for the late response. You are right, we are describing exactly this in the MSTG but it is not properly articulated as requirement in the MASVS. Thanks for pointing out the inconsistency. I just added requirement 2.2 No sensitive data should be stored outside of the app container https://github.com/OWASP/owasp-masvs/commit/f1168bdf69052f0fa8c9dcb21866eaf18bbf79af

For the other suggestion "Encrypt any locally stored files, and store the key appropriately":
We shouldn't suggest in the MASVS to encrypt any locally stored files, but encourage to encrypt sensitive information, as described in 2.1. Therefore this is already addressed in the MASVS.

What do you think?

**Comment by sushi2k** [comment]
@jmanico Agree, that app container is a generic term and only really applies to Android. As on Android you would encrypt data with the key that is stored in the KeyStore, so the data shouldn't leave the app container. For iOS the data would ideally be stored in the KeyChain. 

I just commited the following additional requirement https://github.com/OWASP/owasp-masvs/commit/72c4acf80f897c847bdb34ec3703132192578c39

**Comment by TheDauntless** [comment]
@sushi2k Looks good! 👍 

One nit-picky suggestion would be to change 2.1 to:

System credential storage facilities are used appropriately to store sensitive data, such as **PII,** user credentials or cryptographic keys. | ✓ | ✓ |

**Comment by sushi2k** [comment]
Ok. Done https://github.com/OWASP/owasp-masvs/commit/b564321d33eb6059d07fb393c05eaff5d6bb3a47

Thanks again for your suggestions!
