### ISSUE TITLE
Extend 7.1 with the criteria that the private key should be secured

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-masvs#128]
Can we rewrite `| **7.1** | The app is signed and provisioned with valid certificate. | ✓ | ✓ |` to `| **7.1** | The app is signed and provisioned with valid certificate, of which the private key is properly protected. | ✓ | ✓ |`?

**Comment by sushi2k** [comment]
Merged https://github.com/OWASP/owasp-masvs/commit/9259ec2287b09d0ed5359bead920cae70dbb7934
