### ISSUE TITLE
Add Location-related requirements

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-masvs#131]
The MASVS currently has the focus on securing the data of the user. Next would be to secure the context of a user. Part of that should include the location-related context. We need to:
- reassure that, when the location is involved as a factor, it cannot easily be faked.
- reassure that, when the location is involved, the location data is similarly protected as other data.

**Comment by sushi2k** [comment]
Is this really sth we are considering (or even reliable) on an app level? This might need to be tracked on the API endpoint and trigger alarms via Push Notification/Email if someone is trying to login/triggering functions from a country where the user definitely cannot be at the moment.

**Comment by sushi2k** [comment]
Wouldn't this be part of 4.11? It doesn't clearly cover your suggestion, but maybe we adjust this requirement instead of creating a new one? 

4.11 | The app informs the user of all login activities with their account. Users are able view a list of devices used to access the account, and to block specific devices.
-- | --

**Comment by commjoen** [comment]
Not so sure about it, i rather have it as a separate item. See for instance the pokemon games where users try to spoof their location to cheat the game (and there are quiet some similar games/ideas in there). Next, think about navigation apps which are cheated in order to steer a user to a wrong place.

**Comment by commjoen** [comment]
Meeting notes:
- given the current complexities of location services (E.g. in terms of the threats" gps and their counterbeacons/jammers, network spoofers, Bluetooth beacon copies and their controls on a platform level basis) we are not able to have proper countermeasures on an application level basis. This needs resolution at the vendor/platform level and is out of our control. 
- further controsl about unrealistic movemvent of a user should be implemented in the backend. Note that this is already part of the MSTG (at 4.11 and a few other places).
- we can close the issue.
