### ISSUE TITLE
Requirement 5.6

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-masvs#176]
Requirements 5.6 is defined as follows:
The app only depends on up-to-date connectivity and security libraries.

I think what is actually meant is this:
The app only depends on up-to-date and secure connectivity libraries.

I would propose to change it in this way. Any objections?

**Comment by commjoen** [comment]
Well, having up to date security libraries (openssl/patched security provider) is important as well right?

**Comment by sushi2k** [comment]
I wasn't really thinking about openssl when I was reading security libraries, but of course that makes sense then in this context. So let's close this one.
