### ISSUE TITLE
Minor content fix

### ISSUE THREAD

**Issue by leo860105** [OWASP/owasp-masvs#182]
In Document/0x90-Appendix-A_Glossary, should it be 
"URI/URL fragments" instead of "URI/URL/URL fragments" in the fifth line from the end ?

**Comment by commjoen** [comment]
There are differences in URIs and URLs, therefore we use both here. See https://stackoverflow.com/questions/176264/what-is-the-difference-between-a-uri-a-url-and-a-urn as well...

**Comment by commjoen** [comment]
We might actually change it the other way around: like you can see in #180. Is that ok for you?

**Comment by leo860105** [comment]
Yeah that's great.
Thanks for reply.

**Comment by commjoen** [comment]
Thanks! and thanks again for reporting. Will close it now.
