### ISSUE TITLE
Add an option to generate JSON/XML

### ISSUE THREAD

**Issue by aabashkin** [OWASP/owasp-masvs#204]
Add an option to generate JSON/XML. 

Would be useful for automation/integration with JIRA and other ALMs.

**Comment by commjoen** [comment]
This sounds like a great idea! What do you have in mind? do you want to be able to generate xml/json for every item or just for a selected subset?

**Comment by commjoen** [comment]
So we have a tool `export.py` which you can use, and is referred to the readme, so i guess we have to:
- [ ] Fix the export.py tool (including new langauges)
- [ ] Fix the readme.md on instructions for both the tools folder and the readme in the root

**Comment by commjoen** [comment]
@aabashkin we updated the python tooling again to support this. Please check the README.md and the README.md in the tools section.
Fixed in #230 .
