### ISSUE TITLE
Add a category column to the checklist and also into the MASVS 

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-masvs#205]
See also https://github.com/OWASP/owasp-mstg/issues/1139

**Comment by sushi2k** [comment]
Draft for Category Naming Convention: 

V1: Architecture, Design and Threat Modeling Requirements -> MSTG-ARCH-XX
V2: Data Storage and Privacy Requirements -> MSTG-STORAGE-XX
V3: Cryptography Requirements -> MSTG-CRYPTO-XX
V4: Authentication and Session Management Requirements -> MSTG-AUTH-XX
V5: Network Communication Requirements -> MSTG-NETWORK-XX
V6: Platform Interaction Requirements -> MSTG-PLATFORM-XX
V7: Code Quality and Build Setting Requirements -> MSTG-CODE-XX
V8: Resilience Requirements -> MSTG-RESILIENCE-XX

Once agreed on this, the column "Category" need to be added to all tables in files 0x06 to 0x15 as in https://www.owasp.org/index.php/Testing_Checklist

**Comment by commjoen** [comment]
Just to make sure: is this the first column then?

**Comment by commjoen** [comment]
E.g.:
| # | code | Description | L1 | L2 |
| --- | --- | --- | --- | --- |
| **4.1** | MSTG-AUTH-4.1 | If the app provides users access to a remote service, some form of authentication, such as username/password authentication, is performed at the remote endpoint. | ✓ | ✓ |

**Comment by commjoen** [comment]
Great start! Let me finish it :) so you can focus on the python scripts

**Comment by commjoen** [comment]
Fixed in #230 .
