### ISSUE TITLE
Automate sync of OWASP MASVS Fork with Gitbooks 

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-masvs#215]
The repo https://github.com/sushi2k/owasp-masvs is used for Gitbook. Gitbook needs access to the organisation with the repo and as we cannot give Gitbook access to the OWASP repos (as it will have access to all repos and not only the MSTG and MASVS) I forked it. 

We need an automated sync between https://github.com/OWASP/owasp-masvs and https://github.com/sushi2k/owasp-masvs to push the changes. 

See also: 
https://help.github.com/en/articles/syncing-a-fork

Testing at the moment this Github app https://github.com/wei/pull#readme

**Comment by commjoen** [comment]
So it seems to work again right ;) ?

**Comment by sushi2k** [comment]
Yes, Pull Bot is doing his job :-) Will close this issue. 

https://github.com/sushi2k/owasp-masvs/pull/6/files
