### ISSUE TITLE
Configure .gitbook.yaml for multiple languages in Gitbook

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-masvs#217]
At the moment only english is set as language in Gitbook. Need to change the structure of .gitbook.yaml so it shows all languages and we can navigate through them in Gitbook 

See also: https://docs.gitbook.com/integrations/github/content-configuration

Gitbook link https://mobile-security.gitbook.io/masvs/

**Comment by commjoen** [comment]
Let's make sure that each language includes a changelog at the gitbook page...

**Comment by sushi2k** [comment]
Multi-language is not supported yet in the new Gitbook version https://docs.gitbook.com/v2-changes/important-differences#multi-language-books

Let's postpone to the next release for now. I change the milestone to 1.2

**Comment by commjoen** [comment]
I think we can close this for now, let's revisit the moment we have the feature available...
