### ISSUE TITLE
Translate changelog to Russian

### ISSUE THREAD

**Issue by TheDauntless** [OWASP/owasp-masvs#227]
The changelog is currently not translated to Russian:

https://github.com/OWASP/owasp-masvs/blob/master/Document-ru/CHANGELOG.md

**Comment by RedHotHub** [comment]
> @RedHotHub and @kysokzla can you help with this issue please :) ?

Might we just translate and commit the new changelog.md?
Because I didn't find where it is automatically generating at {{gitbook.time}} stage.

**Comment by commjoen** [comment]
@RedHotHub , currently if there is no changelog.md in your filesystem, it takes the general. So the best would be to copy the CHANGELOG.md from the Document folder and then translate that. Just keep everything inside {{ }} the same so people can track when the version was made 👍

**Comment by commjoen** [comment]
@RedHotHub any updates on this? Feel free to contact me on slack/mail/etc.

**Comment by commjoen** [comment]
Fixed in #328
