### ISSUE TITLE
Add levels to chapter 8 (RE) to give some priority

### ISSUE THREAD

**Issue by TheDauntless** [OWASP/owasp-masvs#256]
Chapter 8 contains many anti RE / device binding / etc controls. It would be nice to have a priority for these items. I suggest we add either levels or a priority to give more guidance.

**Comment by commjoen** [comment]
Meeting notes: Does make sense to me, maybe we can all think a little bit about the levels and do a proposal?

**Comment by commjoen** [comment]
Meeting notes:
- currently we have too few requirements for levelling it easily
- next: the R requirements should _*REALLY*_ be based on a threatmodel. If we want to be able to select the right ones, then we should push for the mobile threat model project. Which is already in the section described.

Closing the issue.
