### ISSUE TITLE
Improve references format & content

### ISSUE THREAD

**Issue by TheDauntless** [OWASP/owasp-masvs#272]
* Make the references consistent in formatting
* Refer to correct locations in MSTG

A few examples of inconsistency:

- Android - <https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05e-Testing-Cryptography.md>
- For Android - <https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md>
- OWASP Mobile Top 10: <https://www.owasp.org/index.php/Mobile_Top_10_2016-M10-Extraneous_Functionality>
- OWASP Mobile Top 10: M8 - Code Tampering: <https://www.owasp.org/index.php/Mobile_Top_10_2016-M8-Code_Tampering>

**Comment by commjoen** [comment]
Excellent! Is there anything left, other than making the translations consistent?

**Comment by commjoen** [comment]
Fixed in the PRs. thanks!
