### ISSUE TITLE
Discussion for MSTG-AUTH-13 (local auth)

### ISSUE THREAD

**Issue by TheDauntless** [OWASP/owasp-masvs#276]
The PR #274 has added the MSTG-AUTH-13 requirement as a result of #189:

> | **4.13** | MSTG‑AUTH‑13 | Local offline authentication of a user towards the mobile app should leverage the APIs offered by the mobile operating system. | ✓ | ✓ |

This seems overkill for level 1 apps (which is all apps). If a basic notes app wants to give you the possibility to add a password to the sqlite where the notes are stored, it would no longer be able to do so. Unless you say that it has to generate a public/private key pair, use that to encrypt the password and store it? For a level 1, it should be "store stuff in your app container". Everything extra is nice to have, or the app is mislabeled as a level 1 app.

I also don't see where this control comes from, as I couldn't find that text in one of the references from #189

**Comment by commjoen** [comment]
Please see https://github.com/OWASP/owasp-masvs/issues/189#issuecomment-516280557 its excel for the rationale :)

**Comment by TheDauntless** [comment]
So this is a result of

> g - In scenarios where offline access to data is needed, add an intentional X second delay to the password entry process after each unsuccessful entry attempt (2 is reasonable, also consider a value which doubles after each incorrect attempt)

For which feedback was provided:

> "As this happens on the device, 4.6 is not applicable. Instead of enforcing a delay of wrong password entries, in this case the app should leverage on OS mechanisms, like Data Protection API on iOS, https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06d-Testing-Data-Storage.md#data-protection-api 
It is already described in the MSTG, but not articulated as requirement  in the MASVS. So this is a gap. 

> We could create another requirement like:
**For offline access of data the app should leverage on existing authentication and data access APIs of the mobile operating system."**

**Comment by commjoen** [comment]
Would you be ok if we enforce it for a lvl 2 app?

**Comment by sushi2k** [comment]
Level 1 is definitely overkill, but it makes sense to put it as a level 2 requirement. 
Offline authentication is not widely used in apps, but we should cover it as requirement in the MASVS.

**Comment by A-AFTAHI** [comment]
So as we all agreed let's add : 

4.13 - For offline access of data the app should leverage on existing authentication and data access APIs of the mobile operating system. (Level 2)
right?

**Comment by TheDauntless** [comment]
Shouldn't we be even more specific? Stating that they have to use the strongest available authentication scheme, or hardware backed authentication?

If you would now encrypt a sqlite db with a pin code, you would be using the Android SDK and you would pass this check.

There is some help from MSTG‑AUTH‑1, but it's not too specific either:

> System credential storage facilities are used appropriately to store sensitive data, such as PII, user credentials or cryptographic keys.

(It's currently not possible to __encrypt__ sqlite through the android sdk, but this is just an example and there will surely be others)

**Comment by commjoen** [comment]
My 2C: I think we should make sure that a hardware backed key is used in the mix to encrypt the local data. This key can only be unlocked by either biometrics/passcode and is some android versions the lockscreen right?

**Comment by TheDauntless** [comment]
Yes, that would make more sense. Something like this?

> | 4.13 | MSTG‑AUTH‑13 | Locally stored sensitive data should be encrypted using a key derived from hardware backed storage |  | ✓ |

This actually raises a different control that I typically report for app assessments:

> Device does not enforce authentication

Without a pincode (or something else), you can't have strong storage. Do we maybe want to add that as well? That would team up rather nicely with the description above.

**Comment by commjoen** [comment]
@sushi2k , @A-AFTAHI : i guess we are taking another turn on this, but implicitly this covers the authentication. The only thing I am afraid of is that the key might be unauthenticated. So we have to (@TheDauntless ) tweak it a little to make it include auth again 💃

**Comment by commjoen** [comment]
> This actually raises a different control that I typically report for app assessments:
> 
> Application does not enforce device authentication
> 
> Without a pincode (or something else), you can't have strong storage. Do we maybe want to add that as well? That would team up rather nicely with the description above.
I would not call it device authentication, but device binding instead. We already cover it in the mstg, but we said in https://github.com/OWASP/owasp-masvs/issues/189 that we would cover that in a separate issue (was in 9, now shifted to 9b)

**Comment by TheDauntless** [comment]
Scratch that, my proposal is covered in 2.11.

@sushi2k  said in the PR:

>  With MSTG-Storage-1 we would say use the Keychain

I don't think it's clear that STORAGE-1 says to use the keychain, just "use them appropriately" (which is rather vague). And on Android, you will have people saying that they can't store stuff in the keystore because only keys are allowed.

I agree that there's overlap, but I think there's a difference between storage requirements for Level 1 and Level 2, which could be made clear through this added control.

**Comment by sushi2k** [comment]
Ok, given that this becomes a level 2 requirement it makes sense to articulate it more strict. Thanks for bringing it up guys. I am fine with the change proposed:

> Locally stored sensitive data should be encrypted using a key derived from hardware backed storage which requires authentication

@TheDauntless If it's not clear in MSTG‑STORAGE‑1 to use the Keychain, do you have any better suggestion? Because this was the original intention of this requirement. Shall we maybe it more clear and get rid of appropriately?

> System credential storage facilities are used appropriately to store sensitive data, such as PII, user credentials or cryptographic keys.

Shall we change it to:

> System credential storage facilities need to be used to store sensitive data, such as PII, user credentials or cryptographic keys.

**Comment by TheDauntless** [comment]
2.1:

> System credential storage facilities need to be used to store sensitive data, such as PII, user credentials or cryptographic keys.

2.x (new), I want to enforce the fact that they should force users to have a pincode on their device, through ksecattraccessiblewhenpasscodesetthisdeviceonly on iOS or setUserAuthenticationRequired on Android

> Sensitive information needs to be stored in system credential storage with full system encryption protection, requiring the user to have a device lock screen enabled.

**Comment by sushi2k** [comment]
Enforcing a pincode is already part of requirement 11:

MSTG‑STORAGE‑11 | The app enforces a minimum device-access-security policy, such as requiring the user to set a device passcode.
-- | --

Having a device passcode is something fundamental that should be enforced on the device. Even if an app is only level 1 the device should be protected with the minimum, which is a passcode. 

Why don't we get the pin/password out of STORAGE-11 and make it part of 2.1 as suggested by Jeroen? For the test case in the MSTG we would just need to delete one line ("- PIN- or password-protected device locking"), see https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#overview-9

If there is sensitive data you would need to use for example the keychain with ksecattraccessiblewhenpasscodesetthisdeviceonly, then it's also only applicable to apps that actually use the keychain and have sensitive data that needs protection.

**Comment by A-AFTAHI** [comment]
I believe that Enforcing security with a pincode is part of the device access security and should not be retrieved from the MSTG-STORAGE-11, while using the system credential storage facilities is another thing.

I suggestion to add more emphasis if you want in the MSTG about the importance of using pincode in the part related to (MSTG-STORAGE-1) but we should not change this on the MASVS. 

What do you think?

**Comment by commjoen** [comment]
After a longer discussion, we for now agreed that:
- you need at least the device passcode to protect the device
- if you need defense in depth, and you have to store data locally (L2), then we do need local authentication based on OS controls (e.g. Auth-12)

**Comment by commjoen** [comment]
Taking this all together in #284: basically the authentication is required to protect data that you still wanted to store offline.
