### ISSUE TITLE
Discussion for MSTG‑STORAGE‑13 (local storage)

### ISSUE THREAD

**Issue by TheDauntless** [OWASP/owasp-masvs#279]
Discussion thread for adding the following L2 control:

> | **2.13** | MSTG‑STORAGE‑13 | No sensitive data should be stored locally on the mobile device. Instead it should be stored at the remote endpoint, and only required data is provided at runtime. |  | ✓ |

I propose we change it to:

> | **2.13** | MSTG‑STORAGE‑13 | No sensitive data should be stored locally on the mobile device. Instead, data should be retrieved from a remote endpoint when needed and only be kept in memory. |  | ✓ |

**Comment by commjoen** [comment]
Fine by me: making it a little sharper, so that you know that there is no caching going on.

**Comment by sushi2k** [comment]
Makes it more clear. Thanks @TheDauntless

**Comment by commjoen** [comment]
Done in #274
