### ISSUE TITLE
Discuss: should we say something about tracking info stored on a device? or about the duration sensitive information is stored on a device?

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-masvs#281]
In the https://github.com/OWASP/owasp-masvs/issues/189 we saw that the Mobile security project has a requirement in not to store sensitive information on the device (e.g. GPS/Tracking) information. Do we want to have another requirement about it? Or do we think that we are covering it well enough?
Maybe we have to just simplify the requirement and say that `sensitive information that has to be available offline should not be stored longer than strictly required`?

**Comment by sushi2k** [comment]
Good idea. Maybe we tweak it a bit? 

> Sensitive information that has to be available offline should not be stored longer than regulations or laws define it.

**Comment by commjoen** [comment]
Sounds like a plan, what do you think @cpholguera & @TheDauntless ?

**Comment by cpholguera** [comment]
Isn't this pretty close to 2.12 (also L2)? Here's a version of both merged:

> No sensitive data should be stored locally on the mobile device (at least no longer than regulations or laws define it). Instead, data should be retrieved from a remote endpoint when needed and only be kept in memory.

**Comment by commjoen** [comment]
MSTG‑AUTH‑12 and MSTG‑STORAGE‑13 and MSTG‑STORAGE‑14 are all possible extension candidates :-)

**Comment by cpholguera** [comment]
I'd also say so, yes

**Comment by sushi2k** [comment]
Combining and integrating into 2.13 sounds good to me.

**Comment by sushi2k** [comment]
@TheDauntless Do you agree with this one?

**Comment by TheDauntless** [comment]
Shouldn't it also be based on the threat model? 

In any case, I would phrase it like this:

> No sensitive data should be stored locally on the mobile device longer than necessary (or allowed by law). Instead, data should be retrieved from a remote endpoint when needed and only be kept in memory.

There's also 2.10 which is comparable, but it's currently about memory instead of storage

> The app does not hold sensitive data in memory longer than necessary, and memory is cleared explicitly after use.

**Comment by commjoen** [comment]
Meeting notes: The requirement is becoming too complicated. Maybe we can move it around and try to extend the MSTG only based on user education and the privacy law requirement?

**Comment by commjoen** [comment]
See https://github.com/OWASP/owasp-masvs/issues/298 as an example of the strategy proposed

**Comment by commjoen** [comment]
Meeting notes:
- when MASVS 1.2 is released we can have the issue at the MSTG (note: @commjoen will move this earlier to make sure that MASVS issues are closed) which focuses on the fact that given privacy laws, we shoudl not hold personal data without a proper processing irght and therefore not forget about removing these type of collectors (app-statisitcs with geolocation, photos with gps location, unless the user wants to have them like that, etc.)

**Comment by commjoen** [comment]
Will be further taken care of at https://github.com/OWASP/owasp-mstg/issues/1491
