### ISSUE TITLE
Discussions: Have requirements on in-app purchases

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-masvs#282]
As from #189: MASVS: maybe we should think about in-app purchases and SMS services via apps a little longer: e.g. have 4.11 on payed materials? -->

After analyzing the older documentation of the mobile security project, we realized that we might want to have a requirement on cost incurring factors for users: should the MASVS dictate anything related to in-app purchases? OR should we just extend MSTG‑STORAGE‑12 its testcase to cover for financial matters and legal matters as well? 
Another direction could be to extend MSTG‑AUTH‑10 to show how it should inform users during in-app purchases or other cost-incuring activities.

Additionally we could say that with a * to the requirement it should include any cost-impeding activities such as an in-app purchase...

**Comment by sushi2k** [comment]
What would be the intention of the requirement? Should it cover:
1. that a user is not able to bypass in-app purchases (with available apps like https://www.luckypatchers.com/download/)
2. that malware cannot abuse in-app purchases / sms services for the attackers benefit
3. just educate the user about potential costs?

For 1.: I think there is not much to do from MASVS point of view, as it seems that there are numerous app that try to bypass in-app purchases and the user would need to disable google play protect, sideload the app and install and use it. It's just one of those cat-and-mouse games and we already have requirements for root detection which many of those apps need. Trying to detect now all of those apps will not make much sense.

For 2.: This would be OS related by keeping the device up-to-date, not root/jb your device and deactivate any security features on purpose (like disabling google play protect). So nothing we can really enforce on the app and therefore we should define in the MASVS

For 3.: Having a history of purchases and educate the user about potential costs in the app would be sufficient. I would say let's extend MSTG-AUTH-11.

**Comment by commjoen** [comment]
I guess we can extend the MSTG in all cases:
1. explain in the MSTG that it is something you need to log/account for
2. true :), which actually translates to 3 so you can see what happened.
3. maybe make sure that educating the user is extended to possible costs when he wants to use the app (mstg)? Even a small note here would be enough, something like `Although not entirely related to educating the user on what happens with his/her data, we do recommend to educate the user on possible costs due to in app purchases` or something like that? Alternatively we could say in the MASVS: `The app educates the user about costs related to the app, the types of personally identifiable information processed, as well as security best practices the user should follow in using the app.`

**Comment by sushi2k** [comment]
Actually adding it to MSTG-STORAGE-12 would be the best. I like your suggestion:

Original:

| **2.10** | MSTG‑STORAGE‑12 | The app educates the user about the types of personally identifiable information processed, as well as security best practices the user should follow in using the app.|  | ✓ |

Change to:

| **2.10** | MASVS-STORAGE-12 | The app educates the user about **costs related to the app**, the types of personally identifiable information processed, as well as security best practices the user should follow in using the app.  | ✓ | ✓ |


@TheDauntless  and @cpholguera what do you guys think?

**Comment by cpholguera** [comment]
I'm only thinking about what costs have to do with storage as this is in the STORAGE category (which of course includes privacy). But I also admit that this one is not really easy to map. So if there's a place now where it could fit it would be there.

Maybe the category should be in the future "Data storage, privacy and user education requirements" if we see that we have several "user education" related requirements? 

For the moment maybe it would be a good idea to include at least a sentence about user education in the "Control Objective" section, that would at least justify why we've included this one here.

**Comment by sushi2k** [comment]
Putting it into the Storage category might be the best place for now, even though that it's not ideal. I also wouldn't know where it fits better ;-) 
But you are right, we should clarify this in the description of V2. 

@TheDauntless Are you ok with this change?

**Comment by commjoen** [comment]
Meeting notes:
- when a transaction happens within the Google/apple store there is a refund policy if this is not the right payment to do
- when you have a malicious transaction, the credit card company will undo this
- when you as a company/app developer want to protect the app from malicious impact, then you should abide by the appstore rules, which are platform features. No need for a requirement here
case closed.
