### ISSUE TITLE
Responsible disclosure requirement

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-masvs#283]
So OWASP/ASVS#664 came back "won't fix". @sushi2k , @TheDauntless , @cpholguera , @A-AFTAHI : what do we do with this? Because having an RD makes sense to me. For now I have set up https://owasp.slack.com/archives/C04T40NND/p1565798928215600 as a discussion within OWASP.

 @sushi2k
 Collaborator Author
sushi2k commented 6 minutes ago • 
Why not put a L1 requirement into V1:

A responsible disclosure policy exists that defines a communication channel to communicate identified vulnerabilities.

In the MSTG we could make a short test case, similar to https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#testing-the-device-access-security-policy-mstg-storage-11.

We could then reference and describe, e.g. https://securitytxt.org/. The security.txt is not a standard yet, but something that is very easy to implement and get's quite some acceptance (at least in the bug bounty community).

I know you don't wan't to have it in the MASVS, but it's part of a application security strategy/program (like threat modeling, which we also have as a requirement).

 @sushi2k
 Collaborator Author
sushi2k commented 23 seconds ago • 
Otherwise we could describe responsible disclosure in the MSTG and just leverage on this requirement in the MASVS:

`| 1.10 | MSTG‑ARCH‑10 | Security is addressed within all parts of the software development lifecycle. | | ✓ |`

Responsible Disclosure is then one way for a feedback loop for the SDLC? I know it's a bit far fetched, but then we at least don't need to touch the MASVS.

 @commjoen
 Member
commjoen commented now
You're right... If no one moves, we should be frontrunner. We could include http://disclose.io/ or https://tools.ietf.org/html/draft-foudil-securitytxt-07  in the MSTG

 @commjoen
 Member
commjoen commented now
As @TheDauntless would say: let's put it in a separate issue 👍

**Comment by sushi2k** [comment]
I would vote for a separate requirement in V1, something like:

> A responsible disclosure policy exists that defines a communication channel to share identified vulnerabilities.

**Comment by cpholguera** [comment]
I like that proposal! what about "to report" instead of "to communicate or share"?

**Comment by commjoen** [comment]
This is still a little vague. I want to make sure that from the app-perspective a researcher can easily see where to report the issue at :) and how to communicate it.
Next, I know many apps are not ready for this, so I rather put it in as L2 for now, as I know we are to "fast" for many companies with this unfortunately (don't get me wrong: I believe in security hygiene including an RD, but I don't want to make people debate politics around RDs because we made it an L1)

**Comment by commjoen** [comment]
`| 1.x| MSTG‑ARCH‑x| A responsible disclosure policy is in place and effectively applied to/integrated into in the app . | | ✓ |`

**Comment by sushi2k** [comment]
True. A RD policy is not something everybody has or can implement easily and might struggle with it, level 2 is sufficient for now. 

Changed it slightly:

| 1.11 | MSTG‑ARCH‑11 | A responsible disclosure policy is in place and effectively applied and integrated into the app . | | ✓ |

**Comment by TheDauntless** [comment]
I like the idea, but I think it's overkill to have it explained in the app itself. Virtually every app has an accompanying website, which is a better place to list that information.

Unless you want to say that the mobile app is integrated into the responsible disclosure scope (so the other way around), but then I would change the phrasing.

**Comment by commjoen** [comment]
good point, so `| 1.x| MSTG‑ARCH‑x| A responsible disclosure policy is in place and effectively applied. | | ✓ |` ?

**Comment by commjoen** [comment]
'added in #310
