### ISSUE TITLE
Sensitive transactions should have non-repudiation covered

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-masvs#286]
Make sure that we have non-repudation covered for sensitive transactions... As having step up might not cover what we actually need by itself...

**Comment by sushi2k** [comment]
But this is stored only on the server-side, so shouldn't this be part of the ASVS anyway?

**Comment by TheDauntless** [comment]
I agree with @sushi2k . If we aren't careful, we'll be recreating the ASVS.

**Comment by commjoen** [comment]
True! Let's close it 👍

**Comment by commjoen** [comment]
I do believe that a mobile app should register its public key if the signing happens at the mobile site. and we should have a date and nounce as well as the message and the signature submitted to the server for checking on it. But that would hold for any frontend executing the signing. so i added my question to the asvs issue :).
