### ISSUE TITLE
Have a requirement on abiding the privacy laws of the country where the app is published

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-masvs#297]
This should include:
- a privacy policy and clearly recorded consent (and its possible withdrawal)
- a proper way to educate the user on what this means.

**Comment by commjoen** [comment]
Meetingnotes:
- could provide a basis for #298
- should be part of ARCH
- possible requirement: 
`1.11 | MSTG‑ARCH‑12 | The app should comply with (privacy) laws and regulations of the country where it is published in. | ✓ | `

- note: check with legal guys on what is the actual state of law: is it where the backends are hosted? or is it where the app is published?

**Comment by A-AFTAHI** [comment]
I'm not a legal expert but i believe that this is way too complicated, and the main raison for that is that laws and regulations are not worldwide unified.

An example of an application published in a country X and the backends in the country Y and each of these too countries has its own regulations and each are willing to apply theirs.

 Noting that there are lots of apps that are used worldwide (ex: Facebook, twitter, etc.).

I believe that the requirement must indicate the obligation of complying with privacy laws but without specifying whether it should be the backend hosting or the publication country, and let the developer or the security tester to choose what laws to follow based on each specific situation.

**Comment by sushi2k** [comment]
Why not simplify it:

 1.11 | MSTG‑ARCH‑12 | The app should comply with privacy laws and regulations. | ✓ |

**Comment by A-AFTAHI** [comment]
> 
> 
> Why not simplify it:
> 
> 1.11 | MSTG‑ARCH‑12 | The app should comply with privacy laws and regulations. | ✓ |

And we can add details in the MSTG on how the developer/security tester should comply with the certain regulations (either the backends hosting or the publication country) based on the context

**Comment by commjoen** [comment]
Makes sense, given https://edpb.europa.eu/sites/edpb/files/files/file1/edpb_guidelines_3_2018_territorial_scope_en.pdf it becomes not so very trivial for GDPR only already.

**Comment by commjoen** [comment]
When we read the full text of https://github.com/OWASP/owasp-mstg/pull/1465 you can see what we follow up on already. So it is covered in the MSTG ^^. However, it would be good to have a basic requirement like `1.12 | MSTG‑ARCH‑12 | The app should comply with privacy laws and regulations. | ✓ | |`

**Comment by commjoen** [comment]
Fixed in #312
