### ISSUE TITLE
have a requirement on not leaking PII through metadata: whether statistics, images, etc.

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-masvs#298]
We should have a requirement that the app should not leak PII through metadata of images, in-app statistics, etc.
This can be location data, name/account info, etc.

**Comment by commjoen** [comment]
Meeting notes:
We do believe that a requirement is necessary, but we don't have a clear solution yet. Will be back in the next meeting.

**Comment by sushi2k** [comment]
We have a requirement about screenshots taken automatically when the app goes to the background. Therefore this one should definitely become its own requirement.
Having meta data in images is exposing sensitive information of the user and will in most cases also leave the device to the server of the app owner, so they should be aware of it.

So we could propose two solutions in the MSTG:
- take a raw image 
- delete exif from the picture taken, like https://stackoverflow.com/questions/32788736/swift-how-to-delete-exif-data-from-picture-taken-with-avfoundation/40417965#40417965

**Comment by commjoen** [comment]
Meeting note:
we do see that it is a good idea to put it in the MSTG as testcases, but the requirement, its level and its phrasing is still hard. Let's put this as a point for our next meeting and see whether we want to have a separate requirement for this indeed.

**Comment by commjoen** [comment]
Good point @cpholguera during the meeting: given https://github.com/OWASP/owasp-masvs/issues/297 we can extend https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04i-Testing-user-interaction.md#testing-user-education-mstg-storage-12 with an explanation on that using the device APIs should be done with care by the developer. It is also fine to have a separate section on this the moment the requirement is enforced.. So plan of action:
1. release MASVS version 1.2 wiht the current issues assigned to it done
2. extend section mentioned above with a part on cleaning images and taking care of application marketing tracking.

**Comment by sushi2k** [comment]
That's a good solution and good place for this, instead of a new requirement.

**Comment by commjoen** [comment]
Will be further taken care of in https://github.com/OWASP/owasp-mstg/issues/1491
