### ISSUE TITLE
Using The MASVS

### ISSUE THREAD

**Issue by stephenreda** [OWASP/owasp-masvs#30]
[https://github.com/OWASP/owasp-masvs/edit/master/Document/0x03-Using_the_MASVS.md#L46](https://github.com/OWASP/owasp-masvs/edit/master/Document/0x03-Using_the_MASVS.md#L46)

"Most attackers are looking for sensitive data that can be used to directly or indirectly profit from to include personally identifiable information and payment data"

This sentence doesn't make sense to me.

**Comment by sushi2k** [comment]
I think the structure of the sentence is just a bit confusing, but has a valid and good point. What do you think about this:

"Most attackers are looking for sensitive data like personally identifiable information (PII) and payment data, that can be used to directly or indirectly profit them."

**Comment by stephenreda** [comment]
agreed, better phrase.

**Comment by b-mueller** [comment]
Updated to:

"Most attackers are looking for sensitive data like personally identifiable information (PII) and payment data that can be used for financial gain."
