### ISSUE TITLE
Improve MASVS: Reiterate over authorization requirements

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-masvs#300]
Right now, I am missing authorization requirements in the masvs as we saw in #189. It would be good to have those as well. Because if you have a multi-user app, you don't want one to be authenticated to get to all data. So maybe we can say something like:
`| 2.x | MSTG‑AUTH‑x| Authorization-models should be defined and enforced at the remote endpoint . | ✓ |  |` ?

**Comment by commjoen** [comment]
Meeting notes:
the requirement is fine as is: we can mr 
`| 2.x | MSTG‑AUTH‑x| Authorization-models should be defined and enforced at the remote endpoint . | ✓ | |`

**Comment by commjoen** [comment]
Fixed in #311

**Comment by TheDauntless** [comment]
Isn't this actually already in MSTG-ARCH-2?

> 1.2 MSTG-ARCH-2 Security controls are never enforced only on the client
side, but on the respective remote endpoints.

**Comment by commjoen** [comment]
the "architecture" is a more general approach. This issue was used to look at the specific authentication and authorization. These are often overlooked. 
Let's close the issue again as this already has been figured out. IF you would like to reorder requirements, let's open a new issue ;-).
