### ISSUE TITLE
Discuss: There should be a requirement about validation of payment receipts on the backend server and not on the device

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-masvs#307]
Discuss: should there be a requirement about validation of payment receipts on the backend server and not on the device?

**Comment by sushi2k** [comment]
This is a more detailed requirement of：
MSTG‑ARCH‑2 | Security controls are never enforced only on the client side, but on the respective remote endpoints. | ✓ | ✓
-- | -- | -- | --


Therefore no need to make an additional requirement, but can be an example in the MSTG for MSTG-Arch-2

**Comment by commjoen** [comment]
Meeting today:
Given that this looks more and more as a 1 out of 1000 example, I say let's clsoe this as we already have examples in the MSTG on related backend enforced items.
