### ISSUE TITLE
Discussion item: Requirements regarding the context of an app

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-masvs#32]
So one control which could really help is ensuring that there are no "fake" or "copied" versions of your app in the app store/play store (nor in the easily-accessible secondary app-stores for Android). Should this control be added?

**Comment by b-mueller** [comment]
Could be a part of V1?

**Comment by sushi2k** [comment]
Good idea. This is really a problem with well known Apps. What do you think about this draft:
"Verify that a process is in place that monitors the available App stores for copied versions of the released App and defines countermeasures to stop the distribution and usage."
What can a company really do if they detect this? They could announce it publicly that there is a fake App to warn their customers and they can contact App Store or Play Store. But is there something else?
Agree with Ben, might be best in V1. Should we classify this as Level 3?

**Comment by commjoen** [comment]
Hope to have a PR about this during this week :)

**Comment by commjoen** [comment]
There are app-store monitoring tools and services by third parties that allow one to make sure that there are no fake apps or copies elsewhere.

**Comment by commjoen** [comment]
@sushi2k when a company notices this, there is often an official takedown request and there are other legal steps that one can take. The rest is actually educating the users (working on that right now between the brucon workshops and talks ;-))

**Comment by commjoen** [comment]
Now that this is merged, @sushi2k & @b-mueller : can we close this item?
