### ISSUE TITLE
Update the Russian version of the MASVS

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-masvs#322]
With version 1.2RC of the MASVS with 13 changes (and are documented at https://github.com/OWASP/owasp-masvs/blob/1.2RC/CHANGELOG.md) all “actual” changes have been captured in `git diff 1.1.4...1.2RC`. It is time for a new translation ;-)

**Comment by commjoen** [comment]
It would be awesome if you could help us once more! We believe that this version of the translation will be much more stable :wink: In order to make sure it becomes easy: please add the following line in your translation, translated to your language:
- Updated the MASVS in the following languages: Chinese (ZHTW), English, German, French, Russian, Spanish, and Japanese) . This way we can simplify the translation process (e.g.: add the line to your changelog when you are done, so that you don’t have to update the translation again :wink: )

**Comment by commjoen** [comment]
Fixed in #328 , thank you @emartynov !

**Comment by commjoen** [comment]
Wrong issue closed, closing #227 now.

**Comment by commjoen** [comment]
Some feedback from @kysokzla at #328: 
Thanks for the translation. I reviewed ur work its good overall but u have to change for sure this lines:

49:
не для авторизации, а для аутентификации - это важно, это разные термины.

48:

в контейнере приложения
тоже самое что и в 49 строчке
** Я не проверял пунктуацию и написание - надеюсь на твою внимательность.

It's a good work after minor changes i think it should be merged in master.

**Comment by kysokzla** [comment]
https://github.com/OWASP/owasp-masvs/pull/333

**Comment by kysokzla** [comment]
Updated https://github.com/OWASP/owasp-masvs/pull/335
Need some review in case of grammar, spelling

**Comment by emartynov** [comment]
Two PRs are added and in review to fix this issue. Please consider moving ticket in project to the review column.

**Comment by emartynov** [comment]
Anything else should be added to #346 ?

**Comment by commjoen** [comment]
Everything seems to be in there. We can close htis down now. Thanks!
