### ISSUE TITLE
Create Korean version of the MASVS (version 1.2RC)

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-masvs#329]
After a great compliancy checklist translation basedn on 1.1.4 of the MASVS, it would be great to have a translation of the MASVS [1.2RC0](https://github.com/OWASP/owasp-masvs/releases/tag/1.2RC) !

With version 1.2RC of the MASVS we get 13 changes (which are documented at https://github.com/OWASP/owasp-masvs/blob/1.2RC/CHANGELOG.md) all “actual” changes have been captured in `git diff 1.1.4...1.2RC`. 

 In order to make sure it becomes easy: please add the following line in your translation, translated to your language:
`- Updated the MASVS in the following languages: Chinese (ZHTW), English, German, French, Japanese, Korean, Russian, and Spanish).`
This way we can simplify the translation process (e.g.: add the line to your changelog when you are done, so that you don’t have to update the translation again 😉 )

**Comment by OWASP-Seoul** [comment]
It is going to translate in November.

**Comment by commjoen** [comment]
@OWASP-Seoul it looks beautiful! Is there anything that needs to happen before we can close this issue?

**Comment by OWASP-Seoul** [comment]
We have finally reviewed the translated version. I think it's okay to close this issue.

**Comment by commjoen** [comment]
Closing it now. Again thank you very much!
