### ISSUE TITLE
Simulator detection is only applicable for Android 

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-masvs#332]
The following requirement is only applicable for Android, but not iOS (for iOS there is only the iOS Simulator as part of Xcode):

8.5 | MSTG‑RESILIENCE‑5 | The app detects, and responds to, being run in an emulator.
-- | -- | --

Should discuss if we want to make it only applicable for Android in the MASVS in the next release:

8.5 | MSTG‑RESILIENCE‑5 | The app detects, and responds to, being run in an emulator (Android only).
-- | -- | --

Question is also if an app can detect that it's running in Corellium (that might the only test case for this requirement).

**Comment by commjoen** [comment]
I don't entirely agree :P... there are simulators upcoming for iOS slowly (Qemu based as well): they're not done by far, but they will eventually be there....

**Comment by sushi2k** [comment]
Fair enough :-)  Let's keep it open and re-assess for the next release if it makes sense or not.

**Comment by cpholguera** [comment]
Since corellium is still around, should we close this @sushi2k ?

**Comment by sushi2k** [comment]
Agree, let's close it.
