### ISSUE TITLE
MIsstype in document name 

### ISSUE THREAD

**Issue by kysokzla** [OWASP/owasp-masvs#334]
Hi i've found that name of the document was mistyped it should be fixed without breaking links etc. In Russian translation same problem - i could fix if it won't break something.
Diffs could break or maybe some book generation scripts.

Document/0x06-V1-Architecture_design_and_threat_modelling_requireme

should be 
Document/0x06-V1-Architecture_design_and_threat_modelling_requirements

**Comment by kysokzla** [comment]
diffs could break

**Comment by commjoen** [comment]
Things to do to fix it:

- [ ] Have an empty file with redirect?
- [ ] Fix the name of the file
- [ ] Fix the name of the file in all Tools scripts (make sure that the old file is excluded from generation)
- [ ] Fix the name of the file/link in the MSTG
- [ ] Check if the playground has any references to the page and fix them

**Comment by cpholguera** [comment]
I agree we should fix this but as everything works just fine right now I suggest shifting this one to 1.3 as the changes might be error prone and we want to ensure a successful 1.2 release. We can gladly discuss it tomorrow :)

**Comment by commjoen** [comment]
After looking at the inconsistencies you showed me, I agree @cpholguera : let's make it part of 1.3 indeed!
