### ISSUE TITLE
Update cover to correspond with the newest version

### ISSUE THREAD

**Issue by emartynov** [OWASP/owasp-masvs#337]
The cover says version 1.1 and 1.2 is going to be published soon.

Also Frontispiece.md stays 2018 and we are at the end of 2019 now.

**Comment by commjoen** [comment]
Next to this, let's make this the release-work ticket:
- [ ] Fix frontispiece and cover
- [ ] Make sure that all languages are named in every translation (it's ok to google translate for now?)
- [ ] Make sure that the fresh translations are added to the tools scripts.

**Comment by emartynov** [comment]
Something off-topic - can we have gitbooks for other languages as well?

**Comment by sushi2k** [comment]
Good question! In the old gitbook version it was available (https://gitbookio.gitbooks.io/documentation/format/languages.html) but they made a relaunch last year and this feature was gone and wasn't added up till now 👎 
I wanted to implement this already a while back, as it would be awesome to have all the different languages also in Gitbook.
If you find something on how to do it with Gitbook, I would be all ears :-)

**Comment by commjoen** [comment]
Fixed in #353 ! Good to release now!
