### ISSUE TITLE
Add Randorisec as Good Samaritan Benefactor

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-masvs#343]
Add Randorisec as Good Samaritan Benefactor See https://github.com/OWASP/owasp-mstg/pull/1601/files for MSTG addition.
- [x] Add logo
- [x] Add header and logo to every translation (google translate?)

**Comment by sushi2k** [comment]
Randorisec is added to:
- German
- English
- Spanish
- French

I couldn't add it to:
- Japanese
- Traditional Chinese
- Russion
- Korean

**Comment by commjoen** [comment]
@coky-t , @emartynov , @ninedter , @OWASP-Seoul can you please help adding our new sponsor to your translations?

**Comment by OWASP-Seoul** [comment]
Add Randorisec as Good Samaritan Benefactor #343 PR.

**Comment by commjoen** [comment]
Jeej! we got them all! WE can close the issue after the final pr has been merged

**Comment by commjoen** [comment]
Will check the Russian translation tonight, but we can close this one now.
