### ISSUE TITLE
Can't join Slack team

### ISSUE THREAD

**Issue by GeedieZ** [OWASP/owasp-masvs#351]
I'd like to contribute and translate your guide to Polish but can't access the slack channel:

"This invite link is no longer active.
If you have an @owasp.org or @owasp.com email address, you can still create an account.
If not, please check with the person who shared the invite link with you to ask for an invitation."

**Comment by commjoen** [comment]
Can you try https://join.slack.com/t/owasp/shared_invite/enQtNjExMTc3MTg0MzU4LWQ2Nzg3NGJiZGQ2MjRmNzkzN2Q4YzU1MWYyZTdjYjA2ZTA5M2RkNzE2ZjdkNzI5ZThhOWY5MjljYWZmYmY4ZjM ?

**Comment by cpholguera** [comment]
Hi @GeedieZ and thanks for reaching out. Aren't you able to create an account with this link?

https://join.slack.com/t/owasp/shared_invite/enQtNjExMTc3MTg0MzU4LTViMDg1MmJiMzMwZGUxZjgxZWQ1MTE0NTBlOTBhNjhhZDIzZTZiNmEwOTJlYjdkMzAxMGVhNDkwNDNiNjZiOWQ

If not, please use this one and let us know if it worked. We might have to update the first one.

Thank you!
https://join.slack.com/t/owasp/shared_invite/enQtNjExMTc3MTg0MzU4LWQ2Nzg3NGJiZGQ2MjRmNzkzN2Q4YzU1MWYyZTdjYjA2ZTA5M2RkNzE2ZjdkNzI5ZThhOWY5MjljYWZmYmY4ZjM

**Comment by GeedieZ** [comment]
I've manage to joined, thanks

**Comment by cpholguera** [comment]
Nice! Did you use the second link? If yes, I'll fix the MASVS straight away with that fix. Thanks in advance.
