### ISSUE TITLE
Mapping to CWE and Mobile Top 10

### ISSUE THREAD

**Issue by lwierzbicki** [OWASP/owasp-masvs#359]
ASVS contains additional column which maps requirement to CWE. I think it is useful (i.e. during report writing or explaining type of vulnerability/weakness).
Maybe it would be good idea to have something similar in MASVS?
What do you think?

ASVS Example: https://github.com/OWASP/ASVS/blob/master/4.0/en/0x10-V1-Architecture.md

**Comment by sushi2k** [comment]
Hi Lukasz,

after discussing internally we came up with the following (draft) solution:

- We do have CWE in the MASVS, but they are very generic (e.g. https://github.com/OWASP/owasp-masvs/blob/master/Document/0x09-V4-Authentication_and_Session_Management_Requirements.md).
- We do have also quite a few CWE’s in the MSTG (e.g. https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#cwe)

The thing is that many of the CWE’s might not be applicable or are more confusing than helpful in the mobile context and for the requirements in the MASVS.

What we should do is:
- [ ] Only MASVS has the mapping to Mobile Top 10 (this seems to be also inconsistent at the moment (for example Android Data Storage maps to M1 and M2 from Mobile Top 10, but MASVS data storage only maps to M2, https://github.com/OWASP/owasp-masvs/blob/master/Document/0x07-V2-Data_Storage_and_Privacy_requirements.md and https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#owasp-mobile-top-10-2016)
- [ ] Only MASVS has the mapping to CWE and we merge and combine the CWE’s from MSTG as a list at the end of MASVS, but not directly to a requirement as there will be a lot of gaps. 
- [ ] We remove the references in the MSTG from CWE and Mobile Top 10, as we anyway never map them to a specific test case.

**Comment by lwierzbicki** [comment]
I gathered CWE and Mobile Top 10 references from MSTG and my notes - it is available here: https://github.com/lwierzbicki/owasp-masvs/tree/cwe
Could you create branch 'cwe' in owasp-masvs? That give me ability to push it and not mess with release version.

Then I will focus on removing references to CWE and Mobile Top 10 from MSTG.

**Comment by commjoen** [comment]
That's an excellent idea @lwierzbicki ! Thank you for being so careful ! Can you fork/create a merge request against https://github.com/OWASP/owasp-masvs/tree/359-cwe please?

**Comment by lwierzbicki** [comment]
PR to 359-cwe branch was raised. If you notice an issue, please let me know (and I will try to correct).

**Comment by sushi2k** [comment]
@lwierzbicki Thanks for the PR! 
Can you please add the CWE also to the simplified Chinese translation (we had traditional chinese, but I just merged the simplified Chinese version https://github.com/OWASP/owasp-masvs/tree/master/Document-zhcn

Can you then please also remove the CWE and OWASP Mobile Top 10 from the MSTG?

**Comment by lwierzbicki** [comment]
I also added commit, which adds CWE and OWASP Mobile Top 10 to simplified Chinese version.

**Comment by sushi2k** [comment]
Awesome! All done and merged. Thanks :-)
