### ISSUE TITLE
copy image folder into zhcn translation

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-masvs#368]
- [x] The image folder is missing. For now the one from the original english version should be copied into zhcn translation
- [x] Add you all as translators: https://github.com/OWASP/owasp-masvs/blob/master/Document-zhcn/0x02-Frontispiece.md#%E8%87%B4%E8%B0%A2

**Comment by commjoen** [comment]
Which parts of this ticket are still open?

**Comment by sushi2k** [comment]
Image folder is there. I added the simplified chinese authors to all MASVS versions. See PR and please approve

**Comment by commjoen** [comment]
Approved

**Comment by sushi2k** [comment]
And merged :-) Thanks
