### ISSUE TITLE
MSTG-CRYPTO-1 - question hardcoded vs static

### ISSUE THREAD

**Issue by lwierzbicki** [OWASP/owasp-masvs#382]
I encountered following situation of Android application:
Application has a file which contains a key used for encryption (it is in apk file and in app container as well). From my perspective it is hardcoded key and additionally static (as it is shared between many instances of app).

When I look at MSTG-CRYPTO-1 it says about hardcoded key. So the question is: does it imply static? And does it work the other way - static implies hardcoded.

I think, from security perspective both are in-secure. Maybe it would be a good idea to clarify this in MSTG-CRYPTO-1.

**Comment by commjoen** [comment]
Hi @lwierzbicki : how is the key defined? For us hardcoded can go in many ways:
- as part of application resources
- as part of a static identifier (which might not be clearly within the definition)
- hardcoded in code

**Comment by commjoen** [comment]
Additionally, we might want to extend it with not having hardcoded/static IVs :)

**Comment by lwierzbicki** [comment]
@commjoen - in mentioned situation, the key is part of application resources.

**Comment by commjoen** [comment]
That is both hardcoded and static. In my opinion it is ok to keep the requirement as is. Static keys are covered by mstg-crypto-3 (e.g. having easily predictable derived keys such as using an app identifier as a key)

**Comment by commjoen** [comment]
Still a good question though... the longer I think about it the more I guess the difference should be explained in the mstg :-)

**Comment by lwierzbicki** [comment]
@commjoen  - it was my thought too. Additionally, I'm working for Android crypto update - so I'm spinning around this topic. I would add your comment to mstg (at least explaining what we mean by hardcoded). That would help testing for MSTG-CRYPTO-01 and MSTG-CRYPTO-03.

All, what do you think?

**Comment by commjoen** [comment]
Sounds like a plan to me! @sushi2k & @cpholguera you agree?

**Comment by cpholguera** [comment]
Agree to that. Thanks for taking the time to give it a good thought :)

**Comment by commjoen** [comment]
Moving this to the MSTG then and closing the issue. Thanks @lwierzbicki !
