### ISSUE TITLE
Invite Link Expired

### ISSUE THREAD

**Issue by rockarts** [OWASP/owasp-masvs#405]
The invite link to slack has expired https://mobile-security.gitbook.io/mobile-security-testing-guide/0x02-frontispiece

**Comment by sushi2k** [comment]
Thanks for pointing out. The URL was still wrong in the MSTG, I created a PR https://github.com/OWASP/owasp-mstg/pull/1674

This is the correct invite: https://owasp-slack.herokuapp.com/
