### ISSUE TITLE
Inconsistency in requirement 2.8 between Gitbook and CSV file.

### ISSUE THREAD

**Issue by paaff** [OWASP/owasp-masvs#408]
Hello! First of all, awesome work - I'm such a big fan :D!

After reading MASVS on Gitbook and also downloading the CSV file of the MASVS requirements, I think I've found a inconsistency between the two on point 2.8 MSTG-STORAGE-8.

In section V2 in the [Gitbook](https://mobile-security.gitbook.io/masvs/security-requirements/0x07-v2-data_storage_and_privacy_requirements) you can see that 2.8 is only set to be required on L2. 

In the CSV file [OWASP_MASVS-v1.2-en.csv](https://github.com/OWASP/owasp-masvs/releases/download/v1.2/OWASP_MASVS-v1.2-en.csv) you can see that 2.8 has the `TRUE` value for both L1 and L2.

I haven't made a PR since I don't know which is correct :D

**Comment by commjoen** [comment]
There seems to be a generation issue: V5.4, has the same issue. Something goes wrong when the tooling parses it...
@TheDauntless, @sushi2k & @cpholguera : do you know what might go wrong here?

**Comment by sushi2k** [comment]
First of all thanks for pointing out @paaff ! The source of truth is definitely our markdown files in Github, and therefore also the Gitbook which is synced after every commit/PR. 

I was also going through the whole CSV and there seems to be two inconsistencies (as Jeroen already pointed out). 

This is how it should be:

|# | MSTG-ID | Description | L1 | L2
|-- | -- | -- | -- | --
|2.8 | MSTG-STORAGE-8 | No sensitive data is included in backups generated by the mobile operating system. |   | ✓


|# | MSTG-ID | Description | L1 | L2
|-- | -- | -- | -- | --
|5.4 | MSTG-NETWORK-4 | The app either uses its own certificate store, or pins the endpoint certificate or public key, and subsequently does not establish connections with endpoints that offer a different certificate or key, even if signed by a trusted CA. |   | ✓


But this is how it is represented in the CSV:


|id | text | category | L1 | L2 | R
|-- | -- | -- | -- | -- | --
|2.8 | No sensitive data is included in backups   generated by the mobile operating system. | MSTG-STORAGE-8 | TRUE | TRUE | FALSE
|5.3 | The app verifies the X.509 certificate of   the remote endpoint when the secure channel is established. Only certificates   signed by a trusted CA are accepted. | MSTG-NETWORK-3 | TRUE | TRUE | FALSE

We will discuss this in our weekly call. At the moment I do not have an answer for this.

**Comment by paaff** [comment]
Thank you for the quick response - I will take the Gitbook as truth then ;)

I hope you find the source of the problem :)

**Comment by sushi2k** [comment]
Our friend Jeroen fixed it :-) 
https://github.com/OWASP/owasp-masvs/pull/410

**Comment by commjoen** [comment]
@sushi2k can you replace the sven,Json and XML files in the release please?
