### ISSUE TITLE
MASVS translation in Hindi

### ISSUE THREAD

**Issue by gitmukeshsharma** [OWASP/owasp-masvs#415]
Hi,
I would like to contribute a translation of the MASVS guide in Hindi.

Thanks,

- [x] translate 0x01-Foreword.md (@gitmukeshsharma )
- [x] review 0x01-Foreword.md (@kunwar-atul-hax0r )
- [x] translate 0x02-Frontispiece.md (@kunwar-atul-hax0r )
- [x] review 0x02-Frontispiece.md (@gitmukeshsharma )
- [x] translate 0x03-Using_the_MASVS.md (@HypnoticLemon )
- [x] review 0x03-Using_the_MASVS.md (@kunwar-atul-hax0r )
- [x] translate 0x04-Assessment_and_Certification.md (@parag85 )
- [x] review 0x04-Assessment_and_Certification.md (@kunwar-atul-hax0r )
- [x] translate 0x06-V1-Architecture_design_and_threat_modelling_requireme.md(@RiteshSSCBS )
- [x] review 0x06-V1-Architecture_design_and_threat_modelling_requireme.md (@kunwar-atul-hax0r )
- [x] translate 0x07-V2-Data_Storage_and_Privacy_requirements.md (@gitmukeshsharma)
- [x] review 0x07-V2-Data_Storage_and_Privacy_requirements.md (@kunwar-atul-hax0r)
- [x] translate 0x08-V3-Cryptography_Verification_Requirements.md (@RiteshSSCBS )
- [x] review 0x08-V3-Cryptography_Verification_Requirements.md (@kunwar-atul-hax0r)
- [x] translate 0x09-V4-Authentication_and_Session_Management_Requirements.md (@HypnoticLemon )
- [x] review 0x09-V4-Authentication_and_Session_Management_Requirements.md
- [x] translate 0x10-V5-Network_communication_requirements.md (@RiteshSSCBS )
- [x] review 0x10-V5-Network_communication_requirements.md (@kunwar-atul-hax0r )
- [x] translate 0x11-V6-Interaction_with_the_environment.md (@Devendrakumarsinha)
- [x] review 0x11-V6-Interaction_with_the_environment.md (@gitmukeshsharma )
- [x] translate 0x12-V7-Code_quality_and_build_setting_requirements.md (@RiteshSSCBS )
- [x] review 0x12-V7-Code_quality_and_build_setting_requirements.md (@kunwar-atul-hax0r )
- [x] translate 0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md (@gitmukeshsharma )
- [x] review 0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md (@RiteshSSCBS )
- [x] translate 0x90-Appendix-A_Glossary.md (@RiteshSSCBS )
- [x] review 0x90-Appendix-A_Glossary.md (@gitmukeshsharma )
- [x] translate 0x91-Appendix-B_References.md (@RiteshSSCBS)
- [x] review 0x91-Appendix-B_References.md (@kunwar-atul-hax0r )
- [x] translate CHANGELOG.md (@RiteshSSCBS )
- [x] review CHANGELOG.md (@gitmukeshsharma )
- [x] translate GLOSSARY.md (@RiteshSSCBS )
- [x] review GLOSSARY.md (@gitmukeshsharma )
- [ ] fix PDF rendering

**Comment by commjoen** [comment]
Hi @gitmukeshsharma that would be awesome!
Best is to check https://github.com/OWASP/owasp-masvs/blob/master/CONTRIBUTING.md on the steps to take :). Do you have a fellow translator and/or reviewer already?

**Comment by gitmukeshsharma** [comment]
Hi Jeroen,
Thanks for the reply. I have gone through the link and the first step was to create the new issue so i have created #415 request.I have also created the git account and configured it.I don't have any fellow translator or reviewer yet.

**Comment by commjoen** [comment]
Hi @gitmukeshsharma ,
You're welcome! are you on OWASP Slack? would be great to have a chat about this ;-).

**Comment by gitmukeshsharma** [comment]
Yes, i am on OWASP slack. My mail id is mail.mukeshsharma@gmail.com.

**Comment by Devendrakumarsinha** [comment]
Hiii, 
I want to I attended traning by sven at OWASPSEASIDES INTERNATIONAL CONFERENCE GOA 2020, i am really interested.

**Comment by commjoen** [comment]
Excelent @Devendrakumarsinha , are you on OWASP Slack? Would love to get in touch with you!

**Comment by Devendrakumarsinha** [comment]
Hi Jeroen, requesting you to send me slack invite , my mail id is - devendrasinha.me@gmail.com

**Comment by commjoen** [comment]
Hi @Devendrakumarsinha , does https://owasp-slack.herokuapp.com/ work for you :) ?

**Comment by Devendrakumarsinha** [comment]
Done👍

**Comment by Devendrakumarsinha** [comment]
thanks
