### ISSUE TITLE
Mistype in "0x03-Using_the_MASVS" chapter

### ISSUE THREAD

**Issue by nameddorna** [OWASP/owasp-masvs#416]
Hi, while translating third chapter i've notice that word "successfully" has been mistyped. here is the paragraph:

MASVS-L2 introduces advanced security controls that go beyond the standard requirements. To fulfill MASVS-L2, a threat model must exist, and security must be an integral part of the app's architecture and design. Based on the threat model, the right MASVS-L2 controls should have been selected and implemented **succesfully**. This level is appropriate for apps that handle highly sensitive data, such as mobile banking apps.

**Comment by commjoen** [comment]
Nice catch! Can you fix the misspelling please either in a translation or separate pr please :-)?

**Comment by nameddorna** [comment]
> 
> 
> Nice catch! Can you fix the misspelling please either in a translation or separate pr please :-)?

Yes, sure!

**Comment by TheDauntless** [comment]
Has been fixed.
