### ISSUE TITLE
2.14: Verify minimal device access-security policy

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-masvs#43]
I think this one of the most important controls and should be mandatory from level 2 if the device supports it. What do you think?

For example, from iOS 8 it can be checked by adding a KeyChain item with the kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly  protection level:

https://github.com/liamnichols/UIDevice-PasscodeStatus

**Comment by stephenreda** [comment]
Does Android has this kind of feature?

**Comment by commjoen** [comment]
In android you can ask the KeyguardManager (see: https://developer.android.com/reference/android/app/KeyguardManager.html for more details).
I always find it hard to say that it needs to be there on medium-level (l2) apps, l3/l4 sounds legit to me, but l2? What if the user does not care for locking his device and all of all sudden would be required to do this by something like a chat app? is that not a little weird?

**Comment by b-mueller** [comment]
True, level 3 is more appropriate. Changed from L4 -> L3.
