### ISSUE TITLE
Crypto requirements - key rotation

### ISSUE THREAD

**Issue by lwierzbicki** [OWASP/owasp-masvs#433]
During reading crypto requirements, I cannot find requirement which is related to key rotation (changing key and its related and appriopate time length when key is used). I started to consider this from key lifecycle and I think it is missing here.

Related guide [NIST SP800-175B chapter 5.1.1](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-175Br1.pdf)

**Comment by commjoen** [comment]
Good point: either we extend MSTG-CRYPTO-5 or create a new requirement 👍
