### ISSUE TITLE
0x07-V2.1 (Data Storage and Privacy requirements)

### ISSUE THREAD

**Issue by litsnarf** [OWASP/owasp-masvs#44]
Think we have to divide point 2.1 (Verify that system credential storage facilities are used appropriately to store sensitive data, such as user credentials or cryptographic keys) in two:
- Tests focused to verifying that the system facilities are in place
- Tests to verify that no sensitive data are stored

The two are strictly related, but different.

**Comment by commjoen** [comment]
I think that the intention was a little different: if you store sensitive data, then please use the system credential storage facilities (keychain, secure enclave for ios and TEE/keychain for iOS). 
I would keep this requirement and say that for level 4 apps there should not be any sensitive data stored (e.g. all stuff that is level 4 should not remain on the device).

**Comment by commjoen** [comment]
But like in #31: this requirement shows a lot of confusion. So we should indeed adjust it :).

**Comment by b-mueller** [comment]
Let's continue this discussion in #31
