### ISSUE TITLE
Translate to Brazilian Portuguese

### ISSUE THREAD

**Issue by mpolastro** [OWASP/owasp-masvs#449]
Translate to brazilian portuguese (pt-br).

**Comment by commjoen** [comment]
Thank you very much @mpolastro ! Let's make some noise about it!

**Comment by commjoen** [comment]
Steps to take:

- [ ] Create an MR with a copy of the Document folder in Document-ptbr
- [ ] Signal us to extend the tooling (link checking, build, etc.)
- [ ] Start the translation & organize your crew at https://owasp.slack.com/archives/C013RBWR8TH ^^

**Comment by SubaruSama** [comment]
Hey i'm down to this!
I can help by July if it's not a problem

**Comment by commjoen** [comment]
New steps: translate and creae MRs :D

**Comment by commjoen** [comment]
Just to make sure: can we get an overview of the updated names of all the translators so we can add them to all translations :) ?

**Comment by mpolastro** [comment]
> Just to make sure: can we please get an overview of the updated names of all the translators so we can add them to all translations :) ?

These are the contributors: Mateus Polastro, Humberto Junior, Rodrigo Araujo, Maurício Ariza, Fernando Galves

**Comment by SubaruSama** [comment]
Hello, can I join in to help in translation to Brazilian Portuguese?
