### ISSUE TITLE
Не верно указана ссылка 

### ISSUE THREAD

**Issue by S4Superbia** [OWASP/owasp-masvs#460]
Здесь - https://github.com/OWASP/owasp-masvs/blob/master/Document-ru/0x12-V7-Code_quality_and_build_setting_requirements.md
Вот тут
OWASP MSTG содержит подробные инструкции по проверке требований, перечисленных в этом разделе.

Android: Тестирование качества кода и настроек сборки - https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05i-Testing-Code-Quality-and-Build-Settings.md
iOS: Тестирование качества кода и настроек сборки - https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05i-Testing-Code-Quality-and-Build-Settings.md

Не верно указана ссылка для ios. Нужно сделать https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06i-Testing-Code-Quality-and-Build-Settings.md

**Comment by commjoen** [comment]
Hi @S4Superbia ! Thank you for reporting the issue 👍

**Comment by commjoen** [comment]
Added a fix in https://github.com/OWASP/owasp-masvs/pull/465
