### ISSUE TITLE
React Native and Flutter are not hybrid as per the given definition

### ISSUE THREAD

**Issue by mrrenaud** [OWASP/owasp-masvs#461]
https://github.com/OWASP/owasp-mstg/blob/1.1.3/Document/0x04a-Mobile-App-Taxonomy.md#hybrid-app

Hybrid apps are described this way : 

> A hybrid app executes like a native app, but a majority of the processes rely on web technologies, meaning a portion of the app runs in an embedded web browser (commonly called “webview”)

But this is not true for framework such as React Native, Flutter or even Xamarin. They may have 3 different approaches, but none of them uses an embedded browser.

Do you think it would be interesting to clarify that point, and maybe introduce a new category?

**Comment by commjoen** [comment]
Good point. Even though older hybrid approaches took this path, modern frameworks do it way different. What would you suggest to explain this in a better way without getting too detailed?

**Comment by mrrenaud** [comment]
_Sorry, I just realized I opened the issue on the wrong repository. Do you prefer to close this one and reopen an issue on the other one?_

In my opinion, the problem is the term native. In what way a Xamarin Android / iOS app is less native than an app built in Swift or in Kotlin ? The binaries will be the same. There's a difference in the language and the tools that are used to develop, build the app and produce the final package. But that's all. 

It would be the same as saying than a web app developed with Typescript is not a "native" web application, compared to something written in JavaScript.


I would suggest something like this : 

> We use to qualify as "Native" a mobile application that is written with the vendor's official programming language, and built with the vendor's official toolchain. However, there are alternative frameworks and toolchains that allow to use a different programming language, and produce almost the same binaries as the official tools. We can mention : 
> 
> - Xamarin
> - React Native
> - Flutter

This is not 100% accurate I know, there are still differences between Xamarin, React Native and Flutter. Flutter is especially different as it's not using the real native UI controls from the vendor's SDK but drawing similar UI on a canva instead.

**Comment by commjoen** [comment]
Good suggestion, 👍  maybe we can indeed continue at the MSTG its repo as we might need to delve in a little deeper. After all some of the issues that we face with hybrid applications using the webview as their main access to content are still worth noting. I guess we might have to iterate over the definition a bit as defining the "modern hybrid" can be a bit tricky in an opinionated world ^^.

**Comment by commjoen** [comment]
First things first: let's have an issue at the MSTG its repo so i can link to it and close this one ^^.

**Comment by commjoen** [comment]
Closing this as we can continue at https://github.com/OWASP/owasp-mstg/issues/1787
