### ISSUE TITLE
Translate to Portuguese (Portugal)

### ISSUE THREAD

**Issue by fjsnogueira** [OWASP/owasp-masvs#467]
Translate to portuguese (pt-pt).

**Comment by commjoen** [comment]
Next steps:
- [ ] Get more people in? (still required? shall we linkedin/tweet about it?)
- [ ] Translate 
- [ ] Start creating the required documents with added scripting when we have some translated content

**Comment by commjoen** [comment]
For those interested to join: check out this Slack channel: https://owasp.slack.com/archives/C017DJKNP60, not a member yet of the OWASP Slack? You can sign up via https://owasp-slack.herokuapp.com/
