### ISSUE TITLE
Outdated NIST link in V1

### ISSUE THREAD

**Issue by julepka** [OWASP/owasp-masvs#501]
The V1 has an outdated link to NIST SP 800-57
Old link: http://csrc.nist.gov/publications/nistpubs/800-57/sp800-57-Part1-revised2_Mar08-2007.pdf
New link: https://csrc.nist.gov/publications/detail/sp/800-57-part-1/rev-5/final
Or a new direct pdf link: https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57pt1r5.pdf

**Comment by cpholguera** [comment]
Hi @julepka, could you please open a PR for this (I'd say with the first link)? that'd be very helpful, thanks for reporting :)
