### ISSUE TITLE
Error generating pdf documents. ./run_docker_masvs_generation_on_local.sh: No such file or directory

### ISSUE THREAD

**Issue by fgalves** [OWASP/owasp-masvs#531]
I am trying to execute the commands according to [README.md](https://github.com/OWASP/owasp-masvs/blob/master/README.md) file (_Create new PDF, Epub, Mobi, and Word document_) to generate the PDF Documents, but the run_docker_masvs_generation_on_local.sh script does not exist:

`juice-sh:/opt # git clone https://github.com/OWASP/owasp-masvs/`
`Cloning into 'owasp-masvs'...`
`remote: Enumerating objects: 14303, done.`
`remote: Counting objects: 100% (930/930), done.`
`remote: Compressing objects: 100% (280/280), done.`
`remote: Total 14303 (delta 628), reused 911 (delta 618), pack-reused 13373`
`Receiving objects: 100% (14303/14303), 102.57 MiB | 1.29 MiB/s, done.`
`Resolving deltas: 100% (10421/10421), done.`
`juice-sh:/opt # cd owasp-masvs/tools/docker`
`juice-sh:/opt/owasp-masvs/tools/docker # ./run_docker_masvs_generation_on_local.sh LATEST`
**`**bash: ./run_docker_masvs_generation_on_local.sh: No such file or directory**`**
`juice-sh:/opt/owasp-masvs/tools/docker # `

To do a double check, I have executed the _ls_ command on the tools/docker folder, but the script _**_run_docker_masvs_generation_on_local.sh_**_ is not there:

`juice-sh:/opt/owasp-masvs # cd tools/docker/`
`juice-sh:/opt/owasp-masvs/tools/docker # ls`
`Dockerfile  SourceSansPro-It.otf  first_page.tex    latex-header.tex`
`README.md   cover.tex             imagereplace.sed  pandoc_makedocs.sh`
`juice-sh:/opt/owasp-masvs/tools/docker #`

**Comment by sushi2k** [comment]
Thanks for raising! This was not updated yet. Please see the PR for the fix https://github.com/OWASP/owasp-masvs/pull/534

**Comment by sushi2k** [comment]
It's merged. Please try again https://github.com/OWASP/owasp-masvs#create-new-pdf-epub-and-word-document

**Comment by fgalves** [comment]
Now, I have received another error. The instructions oriented me to run the file ./tools/docker/pandoc_makedocs_local.sh, but this file does not exist:

`juice-sh:/opt` # git clone https://github.com/OWASP/owasp-masvs/`
`Cloning into 'owasp-masvs'...`
`remote: Enumerating objects: 14377, done.`
`remote: Counting objects: 100% (1004/1004), done.`
`remote: Compressing objects: 100% (325/325), done.`
`remote: Total 14377 (delta 675), reused 955 (delta 647), pack-reused 13373`
`Receiving objects: 100% (14377/14377), 102.59 MiB | 9.91 MiB/s, done.`
`Resolving deltas: 100% (10468/10468), done.`

`juice-sh:/opt # cd owasp-masvs`
`juice-sh:/opt/owasp-masvs # ./tools/docker/pandoc_makedocs_local.sh Document-de LATEST`
`bash: ./tools/docker/pandoc_makedocs_local.sh: No such file or directory`

`juice-sh:/opt/owasp-masvs # cd tools/docker/`
`juice-sh:/opt/owasp-masvs/tools/docker # ls`
`README.md  SourceSansPro-It.otf  cover.tex  first_page.tex  imagereplace.sed  latex-header.tex  pandoc_makedocs.sh`

I think the _pandoc_makedocs_local.sh_ file should be _pandoc_makedocs.sh_

**Comment by sushi2k** [comment]
You are absolutely right. We will merge the PR once approved: https://github.com/OWASP/owasp-masvs/pull/548
