### ISSUE TITLE
"Brasilian" Portuguese Translation

### ISSUE THREAD

**Issue by fgalves** [OWASP/owasp-masvs#532]
The word "**Brasilian**" is misspelled in the file [metadata.md](https://github.com/OWASP/owasp-masvs/blob/master/Document-ptbr/metadata.md) and needs to be changed to **Brazilian**.

After fix it, we need to generate the pt-br pdf file, because its error is on the cover:

![2021_05_13_13_09_14_OWASP_Mobile_Application_Security_Verification_Standard](https://user-images.githubusercontent.com/59673283/118153729-9b0e6e00-b3ec-11eb-84e4-1ebc61137dd8.png)

**Comment by sushi2k** [comment]
Thanks for sharing. We will wait a bit to see if there are more issues raised, then we can release a new minor version.

**Comment by TheDauntless** [comment]
Fixed in #533
