### ISSUE TITLE
Make local build working for non macOS

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-masvs#535]
The current description of a local build only covers macOS:

https://github.com/OWASP/owasp-masvs/issues/531 
https://github.com/OWASP/owasp-masvs#create-new-pdf-epub-mobi-and-word-document

The local build should be working for:

- [x] macOS
- [ ] macOS M1
- [x] Linux
- [ ] Windows

**Comment by TheDauntless** [comment]
Extended for Linux, windows will probably be a bit more work :)

**Comment by cpholguera** [comment]
We should try tu run `sed` in the docker container so that the script can be run anywhere.

**Comment by cpholguera** [comment]
Not working on macOS M1. I opened an issue including a solution: https://github.com/dalibo/pandocker/issues/227

**Comment by cpholguera** [comment]
It should work on Windows thanks to #584, could you please test it @sushi2k / @TheDauntless ?

**Comment by cpholguera** [comment]
Testing local M1 build:

PANDOCKER="docker run --rm --volume `pwd`:/pandoc dalibo/pandocker:buster-latest ${PANDOC_PARAMS}"

# remove the HTML comment from \pagebreak
docker run --rm --entrypoint '/bin/sh' --volume `pwd`:/pandoc dalibo/pandocker:buster-latest -c 'sed -i "s##\1#g" Document/*.md'
