### ISSUE TITLE
Pagebreak English version

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-masvs#538]
![image](https://user-images.githubusercontent.com/5951320/118195857-9b574980-b47e-11eb-8e71-7a84dd198b6d.png)

Should be like this 

![image](https://user-images.githubusercontent.com/5951320/118195872-a1e5c100-b47e-11eb-9482-548c95845cc8.png)

**Comment by cpholguera** [comment]
Fixed in 1.4.2

![Screenshot_20220507-101220](https://user-images.githubusercontent.com/29175115/167245545-c96e4d99-216a-4500-97b0-8f54c0b31d3b.jpg)
