### ISSUE TITLE
4.6 - 4.8

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-masvs#54]
| **4.6** | Verify that a second factor of authentication exists at the remote endpoint, and that the 2FA requirement is enforced at the remote end.  |   | ✓ | ✓ | ✓ |

| **4.8** | Verify that step-up authentication is required to enable actions that deal with sensitive data or transactions.  |   |  | ✓ | ✓ |

Not sure if that's a duplicate or not. Can it be merged into a single requirement?

**Comment by commjoen** [comment]
I don't think that they are duplicates. If you use 2FA, then you have to make sure that your backend is involved properly (4.6). 4.8 only states that you need to have step-up authentication when you are dealing with critical actions. For instance: it can well be for 4.8 that you normally can use long-lived sessions without re-authentication (E.g by using refresh tokens), but that for some reason you need to step up and enter an m-pin for instance.

**Comment by b-mueller** [comment]
Ack
