### ISSUE TITLE
Translation problem to Brazilian Portuguese of the MSTG-PLATAFORM items

### ISSUE THREAD

**Issue by fgalves** [OWASP/owasp-masvs#545]
In the page 35, the MSTG-ID MSTG-PLATFORM-1,  MSTG-PLATFORM-2 are correct, but the following MSTG-ID are wrong: (MSTG-PLATAFORMA-3,MSTG-PLATAFORMA-4,MSTG-PLATAFORMA-5,MSTG-PLATAFORMA-6,MSTG-PLATAFORMA-7,MSTG-PLATAFORMA-8,MSTG-PLATAFORMA-9,MSTG-PLATAFORMA-10,MSTG-PLATAFORMA-11). 

The right value should be MSTG-PLATFORM-3, MSTG-PLATFORM-4, MSTG-PLATFORM-5, MSTG-PLATFORM-6, MSTG-PLATFORM-7, MSTG-PLATFORM-8, MSTG-PLATFORM-9, MSTG-PLATFORM-10, and MSTG-PLATFORM-11.

**Comment by sushi2k** [comment]
Good spot, thank you @fgalves! For these small changes you can just open a PR, no need to create an issue for typos.
