### ISSUE TITLE
Email and SMS

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-masvs#55]
| **5.9** | Verify that the app doesn't rely on insecure communication channels (e.g email and SMS) for critical operations, such as enrollments and OTPs. |   |  | ✓ | ✓ |

This is a very impactful requirement and we have to define exactly which communication channels are considered insecure. Saying "for example email and SMS" won't cut it.
Just last week I tested a banking app that used a combination of SMS and email for enrollment. The user would receive an OTP over both channels and have to enter both of them correctly to enroll. This was done only once during the setup phase.
In my opinion, this was more than sufficient for the use case.
What do you think?

**Comment by commjoen** [comment]
Maybe we can say: 
"verify that the app does not rely on a single insecure communication channel (SMS, e-mail) for critical operations, such as enrollments and OTPs". I would not know of other less secure channels which are often used other than SMS and e-mail. But if you want to list them, it might be that you have to continuously re-evaluate the list of items.

This way having multiple channels is still allowed.

**Comment by b-mueller** [comment]
Ok, I changed it along that lines.
