### ISSUE TITLE
Create Check List 

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-masvs#56]
A script should be created that is able to generate a checklist in csv/Excel of all the requirements. 

Maybe 8 sheets and each sheet has the requirements of each section we have at the moment:

V1: Architecture, Design and Threat Modelling Requirements
V2: Data Storage and Privacy Requirements
V3: Cryptography Verification Requirements
V4: Authentication and Session Management Requirements
V5: Network Communication Requirements
V6: Environmental Interaction Requirements
V7: Code Quality and Build Setting Requirements
V8: Resiliency Against Reverse Engineering Requirements

**Comment by boos** [comment]
I have this script, I'll be happy to submit it as soon as possible.

**Comment by b-mueller** [comment]
Yes, please :)

**Comment by boos** [comment]
When OWASP-MSTG will be stable I'll create a script to cross reference both documents and to automatically generate an XLS.
