### ISSUE TITLE
Improve Russian Translation

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-masvs#567]
According to @julepka the Russian Translation should be improved.

This can be done right away or wait for the refactoring to be finished (surely still a couple of months)

**Comment by cpholguera** [comment]
@julepka should I assign it to you?

**Comment by julepka** [comment]
@cpholguera Yes, I'll be glad to improve it

**Comment by cpholguera** [comment]
Then it's all yours, thanks a lot!
