### ISSUE TITLE
[Resiliency Against Reverse Engineering Requirements] Duplication 

### ISSUE THREAD

**Issue by bugwrangler** [OWASP/owasp-masvs#58]
Following requirements should be summarise, these are not 4 unique requirements. 

#**8.3** 
#**8.6**
#**8.10**
#**8.15**

Kindly review and do needful.

**Comment by b-mueller** [comment]
Hi @bugwrangler, the requirements are slightly different - 8.6 requires using _multiple_ different methods of root detection instead of just one, 8.15 requires using _multiple_ different means of emulator detection. Requirements are stronger on higher levels.

**Comment by bugwrangler** [comment]
How about 8.3 and 8.10 ? I feel there is no need of 4 different requirements.
