### ISSUE TITLE
[V7: Code quality and build setting requirements] : Verify that the app is marked as a release build. 

### ISSUE THREAD

**Issue by bugwrangler** [OWASP/owasp-masvs#59]
Could you pls. elaborate this requirement ?

**Comment by sushi2k** [comment]
I guess the main point is that once you make a release build it is signed with the actual key of the developer/company to verify the integrity of the App. If for example an APK would be shipped as debug build the certificate used to sign the App was coming from the IDE (Android Studio) that was used during development.
Nevertheless a debug build cannot be distributed via Play Store, so creating a release build is of course mandatory if an App should be published in an official App store. 

See also:
https://developer.android.com/studio/publish/preparing.html

**Comment by bugwrangler** [comment]
I feel technical term "release build" doesn't denote factual meaning. pls. look up my pull request. 
We should add one/two other requirements w.r.t release build concept including key used to sign build and User / enterprise certificate used for release build etc.

**Comment by sushi2k** [comment]
What do you think of this: https://github.com/OWASP/owasp-masvs/pull/61#discussion-diff-92522756R19

**Comment by bugwrangler** [comment]
Align, thx!
