### ISSUE TITLE
should we be linking Requirements with specific test cases?

### ISSUE THREAD

**Issue by anantshri** [OWASP/owasp-masvs#6]
The discussion at #5 got me thinking should we be linking ASVS Requirements with specific test cases in the MSTG.

advatage: we can keep generic Requirements and still have detailed checks based on OS specific testcases.

**Comment by thec00n** [comment]
I think that's a good approach.

**Comment by b-mueller** [comment]
Yes, definitely!


Get Outlook for Android






On Tue, Sep 13, 2016 at 3:54 PM +0800, "Gerhard" <notifications@github.com> wrote:












I think that's a good approach.

**Comment by stephenreda** [comment]
ok agreed, but this means that we still have a long road ahead with this project ;)
