### ISSUE TITLE
Add Czech Translation

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-masvs#622]
Thanks for translating the MASVS and the Checklists!

First of all fork the project and `git clone` it to your laptop.

![grafik](https://user-images.githubusercontent.com/29175115/151347220-3967d301-ae3d-49d2-bf9c-05d8ace82ce1.png)

1. Create a new branch, e.g. `czech-translation`
2. Copy the content of the original `Document/` and rename it to `Document-cz/`.
3. Commit & push.
4. Modify the `metadata.md` file with the metadata of the new language.
5. Translate all files in the folder. 
6. Open a Pull Request.

If you have any questions or difficulties please let us know. Are you on slack?

You can create an OWASP Slack account here: https://owasp.slack.com/join/shared_invite/zt-g398htpy-AZ40HOM1WUOZguJKbblqkw#// 

And then join our channel here: https://owasp.slack.com/messages/project-mobile_omtg/details/

Or just write to "Carlos" or "Sven", or both :)

**Comment by cpholguera** [comment]
Hi @justmishka, how are you? Do you have any news on this? We're looking forward to having your translation ☺️

**Comment by justmishka** [comment]
Hi, I have it in progress :) 

Now I am finishing my master degree, thats the reason why I did not finalize it yet. But I still would like to complete this task :)

Odesláno z iPhonu

**Comment by cpholguera** [comment]
That's great, thanks a lot for the update @justmishka. I wish you the best for your master thesis!

**Comment by cpholguera** [comment]
Hi @justmishka, I hope everything's going well for you. Do you have anything new on the translation? Thanks!
