### ISSUE TITLE
Add Greek Translation

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-masvs#625]
First of all fork the project and `git clone` it to your laptop.

![grafik](https://user-images.githubusercontent.com/29175115/151347220-3967d301-ae3d-49d2-bf9c-05d8ace82ce1.png)

1. Create a new branch, e.g. `greek-translation`
2. Copy the content of the original `Document/` and rename it to `Document-gr/`.
3. Commit & push.
4. Modify the `metadata.md` file with the metadata of the new language.
5. Translate all files in the folder. 
6. Open a Pull Request.

If you have any questions or difficulties please let us know. Are you on slack?

You can create an OWASP Slack account here: https://owasp.slack.com/join/shared_invite/zt-g398htpy-AZ40HOM1WUOZguJKbblqkw#// 

And then join our channel here: https://owasp.slack.com/messages/project-mobile_omtg/details/

Or just write to "Carlos" or "Sven", or both :)

**Comment by cpholguera** [comment]
Hi @panosylr, how are you? Do you have any news on this? We're looking forward to having your translation ☺️

**Comment by panosylr** [comment]
Hi @cpholguera :) I am doing well; I have left this one in the middle due to a relocation taking place, but now I am settling in, and I will have it finalized by the end of the week

**Comment by cpholguera** [comment]
That's awesome! I'm very glad to hear that. Thanks a lot for the update and if you need any help simply reach out anytime. Have a great week @panosylr!

**Comment by panosylr** [comment]
@cpholguera Submitted pull request for the Greek translation :)

**Comment by cpholguera** [comment]
We really appreciate this, thank you so much for taking the time @panosylr!
