### ISSUE TITLE
Improve Spanish translation of MASVS

### ISSUE THREAD

**Issue by Sulfkain** [OWASP/owasp-masvs#643]
I have some tips to improve a bit the Spanish translation, just to improve comprehesion, sometimes I feel the paragraph is a literal translation from English, some little changes will improve comphesion.

Others changes could be apply to the global section too, for example when you mention a chapter, it will be great if mention the number too.
For example: 
'On the chapter Resilience on apart "Device Binding"' 
VS
'On the chapter Resilence (V8) on apart "Device Binding" (8.10)

Thanks.

**Comment by cpholguera** [comment]
Hi @Sulfkain thanks for your feedback. We'll be happy to review your ideas. Would you mind opening a PR with your proposal? Thank you very much!

**Comment by Sulfkain** [comment]
Hi @cpholguera 
Here you are https://github.com/OWASP/owasp-masvs/pull/645

**Comment by cpholguera** [comment]
Le echaré un vistazo, muchas gracias @Sulfkain!

**Comment by Sulfkain** [comment]
Ok, but if you want, don't close this issue even if you approve the PR, because I can improve more files of MASVS with this issue.

Thanks.

**Comment by cpholguera** [comment]
If they're for Spanish it'd be better to put them all in the same PR. If it's another thing we'd better have different issues+PRs. Just let me know about what you'd like to do and I can help you with organization. Thank you @Sulfkain.

**Comment by Sulfkain** [comment]
I can do it step by step, that is what I prefer to do various PR.
 If you prefer then issue+PR will be no problem, I can create both at the same time (duplicating text+chapter on the issue) ;).
