### ISSUE TITLE
Gitbook still shows 1.3.1 release

### ISSUE THREAD

**Issue by t3chn0m4g3** [OWASP/owasp-masvs#644]
Just noticed the Gitbook version still runs with [1.3.1](https://mobile-security.gitbook.io/masvs/) release instead of 1.4.2.

**Comment by t3chn0m4g3** [comment]
@cpholguera Thank you for the swift response. And yes, I opened the issue based on the changelog.
Thanks for the clarification!

**Comment by cpholguera** [comment]
Thanks to you! I'll leave it open until I come up with a solution for that.

**Comment by cpholguera** [comment]
When we launched the OWASP MAS website, we deprecated gitbook. We removed support for it completely last week.

https://mas.owasp.org/
