### ISSUE TITLE
Link in Readme.md to Read The Owasp MASVS leads to 404 endpoint.

### ISSUE THREAD

**Issue by AndreMCCarvalho** [OWASP/owasp-masvs#670]
In the readme file of the project if we press the big button that says **Read the OWASP MASVS** it leads to a 404. This is the button in question:

![image](https://user-images.githubusercontent.com/38227395/194000724-cf526c77-baee-4cc9-8f15-7cf3a5847da2.png)

**Comment by cpholguera** [comment]
Thank you very much @AndreMCCarvalho! It's fixed now 🚀
