### ISSUE TITLE
incorrect connection to official website

### ISSUE THREAD

**Issue by Cl0udG0d** [OWASP/owasp-masvs#672]
website:https://mas.owasp.org/MASVS/

the simplified Chinese download on the official website does not correspond to the label
![image](https://user-images.githubusercontent.com/45556496/200247915-42c07bec-ddff-404d-8d4f-98d06f791209.png)

you can click Jump to find that this is an incorrect connection：

https://github.com/OWASP/owasp-masvs/releases/latest/download/OWASP_MASVS-v1.4.2-ptbr.pdf

correct connection at
https://github.com/OWASP/owasp-masvs/releases/latest/download/OWASP_MASVS-v1.4.2-zhcn.pdf

**Comment by cpholguera** [comment]
Hi @Cl0udG0d, thanks for reporting this issue. It should be fixed now, could you please verify?

Thanks to you we've fixed 2 additional wrong links.

**Comment by Cl0udG0d** [comment]
that 's great
