### ISSUE TITLE
Removing References to PassionFruit and replace it with Grapefruit

### ISSUE THREAD

**Issue by rsenet** [OWASP/owasp-masvs#685]
Many pages make references to PassionFruit which is deprecated and replaced by Grapefruit:

- https://mas.owasp.org/MASTG/iOS/0x06b-Basic-Security-Testing/#passionfruit
- https://mas.owasp.org/MASTG/iOS/0x06b-Basic-Security-Testing/#listing-installed-apps
- https://mas.owasp.org/MASTG/iOS/0x06b-Basic-Security-Testing/#native-libraries
- https://mas.owasp.org/MASTG/iOS/0x06b-Basic-Security-Testing/#accessing-app-data-directories
- https://mas.owasp.org/MASTG/iOS/0x06b-Basic-Security-Testing/#monitoring-system-logs
- https://mas.owasp.org/MASTG/iOS/0x06b-Basic-Security-Testing/#dumping-keychain-data

A full update cool be intersting

**Comment by cpholguera** [comment]
Hi @rsenet, you're right. Would you mind opening a pull request including the fixes and new information?

The PR should then close this issue as well as #1924

Thanks a lot!

**Comment by cpholguera** [comment]
Closing since this belongs in the MASTG and we already have an issue for this.

https://github.com/OWASP/owasp-mastg/issues/1924
