### ISSUE TITLE
V9: Resiliency Against Reverse Engineering Requirements: nitpicks

### ISSUE THREAD

**Issue by anantshri** [OWASP/owasp-masvs#86]
**requirement 9.1** 

This states we need custom keyboard. how do we test custom keyboards are we covering this anywhere in mstg, also is there a reference implementation. 

When we encouraging people to develop own custom keyboards, aren't this like encouraging themselves to write own crypto. Who will validate the custom keyboards. what if custom keyboard themselves leak the keystrokes

just some concerns.

**Comment by b-mueller** [comment]
Hi Anant, those are valid concerns, we'll have to elaborate on that in the MSTG (actually that's a test case in my "jurisdiction"). There's still a possibility that this requirement turn out not work at all in practice, in which case it will be removed.

**Comment by commjoen** [comment]
Hi @b-mueller : i might be able to help there, I will need to find some time for it.

**Comment by b-mueller** [comment]
@commjoen sure, if you have time! I'm closing this for now, we'll revisit it depending on how the test case in the MSTG develops.
