### ISSUE TITLE
4.2 requires random access tokens where signed access tokens coud also suffice

### ISSUE THREAD

**Issue by Sjord** [OWASP/owasp-masvs#93]
[V4 says](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x09-V4-Authentication_and_Session_Management_Requirements.md):

>4.2. The remote endpoint uses randomly generated access tokens to authenticate client requests without sending the user's credentials.

However, when using a JWT (or any other signed data) as access token it can be secure, but it is definitely not randomly generated. Can this requirement be made more generic so that it includes both random session IDs and JWTs?

**Comment by sushi2k** [comment]
Thanks for bringing this up. 
Just made a PR: https://github.com/OWASP/owasp-masvs/pull/94
What do you guys think? @b-mueller @Sjord

**Comment by jmanico** [comment]
Isn't the whole point of signed JWT's to avoid the need of a session and contain all data needed to verify a claim?

--
Jim Manico

**Comment by sushi2k** [comment]
@jmanico Yes, that's why we were proposing to split requirement 4.2 into two requirements which will be a redefined requirement 4.2 (classic session management) and a new requirements 4.3 (stateless authentication).

Check the PR: https://github.com/OWASP/owasp-masvs/pull/94/files

**Comment by jmanico** [comment]
Awesome!

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by sushi2k** [comment]
Just merged the PR. Thanks again @Sjord for bringing it up.
